image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm install && npm run-script build && npm install -g serve && cd build && wget https://corentv.com/corenshows.db && cd ..
    command: serve -s build
